### ISSUE TITLE
 install error Cannot find module 'tapable'

### ISSUE THREAD

**Issue by GerrieWell** [codeinthedark/editor#4]
```
O_O[23:50:46]editor$ sudo npm install
Password:
npm WARN package.json citd-editor@0.0.1 No repository field.
npm WARN package.json citd-editor@0.0.1 No license field.
^_^[23:51:44]editor$ ./node_modules/.bin/gulp serve
[23:51:49] Requiring external module coffee-script/register
module.js:338
    throw err;
          ^
Error: Cannot find module 'tapable'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Volumes/more/source/tool/editor/node_modules/webpack/lib/Compiler.js:6:15)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Volumes/more/source/tool/editor/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Volumes/more/source/tool/editor/node_modules/webpack/lib/webpack.js:5:16)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Volumes/more/source/tool/editor/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Volumes/more/source/tool/editor/gulpfile.coffee:9:11)
  at Object.<anonymous> (/Volumes/more/source/tool/editor/gulpfile.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Volumes/more/source/tool/editor/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Volumes/more/source/tool/editor/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (/Volumes/more/source/tool/editor/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/Volumes/more/source/tool/editor/node_modules/gulp/node_modules/liftoff/index.js:192:16)
  at module.exports (/Volumes/more/source/tool/editor/node_modu
```
I'm not familiar with npm. How can I install it quickly?

**Comment by GerrieWell** [comment]
just rm module folder and retry.

**Comment by liujb** [comment]
我也遇到这个问题了，也是通过重装解决的。

**Comment by laowenlu** [comment]
@GerrieWell thanks!
